# Generated by Django 3.2.8 on 2021-10-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('kind', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
    ]
