# Generated by Django 3.2.7 on 2021-11-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('kind', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('pictures', models.URLField()),
            ],
        ),
    ]
