# Generated by Django 3.2.8 on 2021-10-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='number',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
