# Generated by Django 3.2.10 on 2021-12-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human_body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_name', models.CharField(max_length=100, unique=True)),
                ('height', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
