# Generated by Django 3.2.10 on 2021-12-14 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DressApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='human_body',
            name='picture',
            field=models.ImageField(default='human_img/default.png', upload_to='human_img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='human_body',
            name='height',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='human_body',
            name='human_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='human_body',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
