# Generated by Django 3.2.10 on 2021-12-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DressApp', '0002_auto_20211214_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human_body',
            name='picture',
            field=models.ImageField(default='human_img/default.png', upload_to='human_img/'),
        ),
    ]
