# Generated by Django 3.2.10 on 2021-12-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DressApp', '0003_alter_human_body_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human_body',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='human_img/'),
        ),
    ]
