# Generated by Django 3.2.10 on 2021-12-15 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DressApp', '0004_alter_human_body_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human_body',
            name='height',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(250)]),
        ),
    ]
