# Generated by Django 3.2.10 on 2021-12-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DressApp', '0007_alter_human_body_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human_materials',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
