# Generated by Django 3.2.10 on 2021-12-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DressApp', '0008_alter_human_materials_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='human_body',
            name='cut_image_path',
            field=models.URLField(default='none_path', max_length=1000),
        ),
        migrations.AddField(
            model_name='human_body',
            name='part_segm_path',
            field=models.URLField(default='none_path', max_length=1000),
        ),
        migrations.AddField(
            model_name='human_body',
            name='skeleton_json_path',
            field=models.URLField(default='none_path', max_length=1000),
        ),
        migrations.AlterField(
            model_name='human_materials',
            name='cut_image_path',
            field=models.URLField(default='none_path', max_length=1000),
        ),
        migrations.AlterField(
            model_name='human_materials',
            name='part_segm_path',
            field=models.URLField(default='none_path', max_length=1000),
        ),
        migrations.AlterField(
            model_name='human_materials',
            name='skeleton_json_path',
            field=models.URLField(default='none_path', max_length=1000),
        ),
    ]
