# Generated by Django 3.2.10 on 2021-12-24 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DressApp', '0009_auto_20211220_0031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Human_materials',
        ),
    ]
