# Generated by Django 3.2.10 on 2021-12-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DressApp', '0010_delete_human_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human_clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_id', models.IntegerField(default=0)),
                ('part_clothes', models.IntegerField(default=0)),
                ('clothes_name', models.CharField(max_length=100)),
                ('match_clothes_path', models.URLField(default='none_path', max_length=1000)),
            ],
        ),
    ]
