# Generated by Django 3.2.9 on 2021-12-14 09:35

from django.db import migrations, models
import stdimage.models
import top.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=30)),
                ('kind', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('picture_detail_url', models.URLField(max_length=1000)),
                ('picture_url', models.URLField(max_length=1000)),
                ('picture', stdimage.models.StdImageField(blank=True, upload_to=top.models.image_directory_path)),
            ],
        ),
    ]
