# Generated by Django 3.2.8 on 2021-11-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0003_auto_20211107_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('kind', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('pictures', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='area',
        ),
        migrations.DeleteModel(
            name='Utility',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Cafe',
        ),
    ]
