# Generated by Django 3.2.9 on 2021-11-22 02:19

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0004_auto_20211107_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='pictures_detail',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloth',
            name='pictures',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images'),
        ),
    ]
