# Generated by Django 3.2.9 on 2021-11-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0004_auto_20211107_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
