# Generated by Django 3.2.9 on 2021-11-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0005_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='cloth',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
