# Generated by Django 3.2.9 on 2021-11-23 03:18

from django.db import migrations, models
import imagekit.models.fields
import top.models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0006_alter_cloth_pictures_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='pictures',
            field=imagekit.models.fields.ProcessedImageField(upload_to=top.models.image_directory_path),
        ),
    ]
