# Generated by Django 3.2.9 on 2021-11-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0006_auto_20211111_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='img',
        ),
    ]
