# Generated by Django 3.2.9 on 2021-11-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0007_remove_cloth_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
