# Generated by Django 3.2.9 on 2021-11-23 04:05

from django.db import migrations
import stdimage.models
import top.models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0007_auto_20211123_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloth',
            old_name='pictures_detail',
            new_name='picture_detail',
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='pictures',
        ),
        migrations.AddField(
            model_name='cloth',
            name='picture',
            field=stdimage.models.StdImageField(blank=True, upload_to=top.models.image_directory_path),
        ),
    ]
