# Generated by Django 3.2.9 on 2021-11-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0008_auto_20211123_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloth',
            old_name='picture_detail',
            new_name='picture_detail_url',
        ),
        migrations.AddField(
            model_name='cloth',
            name='picture_url',
            field=models.URLField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
