# Generated by Django 3.2.9 on 2021-11-27 15:55

from django.db import migrations, models
import stdimage.models
import top.models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0008_cloth_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='img',
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='pictures',
        ),
        migrations.AddField(
            model_name='cloth',
            name='picture',
            field=stdimage.models.StdImageField(blank=True, upload_to=top.models.image_directory_path),
        ),
        migrations.AddField(
            model_name='cloth',
            name='picture_detail_url',
            field=models.URLField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloth',
            name='picture_url',
            field=models.URLField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloth',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
